[package]
name = "BackupTool"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.67"
serde = {version = "1.0.130", features = ["derive"]}
zip = "0.5.13"
chrono = "0.4.19"